const mongoose = require('./mongoose');
const Schema = mongoose.Schema;

const ChatsSchema = new Schema({
    nomeCliente: String,
    numeroCliente: String,
    direciona_setores: [{ type : Schema.Types.ObjectId}],
    direciona_usuarios: [{ type : Schema.Types.ObjectId}],
    cliente_id:{type: Schema.ObjectId, ref: 'clientes'},
    funil_id:{type: Schema.ObjectId, ref: 'funis'},
    criado_por:{type: Schema.ObjectId, ref: 'usuarios'},
    statusRoom:String,
    lastUpdate:Date,
    dataCriacao:Date,
    dataUltimaMensagem:Date,
    dataUltimaAtualizacaoFoto:Date,
    novaMensagem:String,
    lastMessage:String,
    chatbot:Boolean,
    atendimentoAceito:Date,
    historico:Array,
    fotoPerfil:String,
    info:Object,
    isCheckMsgSend:Boolean,
    ticket_active_id:{type: Schema.ObjectId, ref: 'tickets'},
    fv_lead_active_id:{type: Schema.ObjectId, ref: 'fv_leads'},
    Canal: String,
    instagramUser: Object,
    instagram_user_id:String,
    instagram_user:String,
    messenger_user_id:String,
    messenger_user:String,
    canal:String,
    canal_id:{type: Schema.ObjectId, ref: 'canais'},
    origem_criado:String,
    fv_lead_id:{type: Schema.ObjectId, ref: 'fv_leads'},
    tags:[{type: Schema.ObjectId, ref: 'chats_tags'}],
    contato_id:{type: Schema.ObjectId, ref: 'contatos'},
    output_pesquisa:String,
    obs_criacao:String,
    notas:Array,
    statusCustomValue:String,
    transferDate:Date,
    sessionFlowId:String,
    ai_order_lead_id:{type: Schema.ObjectId, ref: 'ai_orders_leads'},
    lastMessageWpp:Object,
    lastDateMsgAgent:Date,
    lastDateMsgClient:Date,
    ai_chats_analysis_id: { type: Schema.ObjectId, ref: 'ai_chats_analysis' },
    isLid:Boolean,
    chatNumber:String,
    chatLid:String,
    wallet_user_id:{ type: Schema.ObjectId, ref: 'usuarios' }
});

module.exports = mongoose.model('chats', ChatsSchema);
