const mongoose = require('./mongoose');
const Schema = mongoose.Schema;

const WhatsappMensagensSchema = new Schema({
  cliente_id: { type: Schema.ObjectId, ref: 'clientes' },
  event: String,
  platform: String,
  session: String,
  id: String,
  body: String,
  type: String,
  t: Number,
  notifyName: String,
  from: String,
  to: String,
  self: String,
  ack: Number,
  isNewMsg: Boolean,
  star: Boolean,
  kicNotified: Boolean,
  recvFresh: Boolean,
  interactiveAnnotations: Array,
  deprecatedMms3Url: String,
  directPath: String,
  mimetype: String,
  filehash: String,
  encFilehash: String,
  filename: String,
  size: Number,
  mediaKey: String,
  mediaKeyTimestamp: Number,
  isViewOnce: Boolean,
  width: Number,
  height: Number,
  staticUrl: String,
  scanLengths: Array,
  isFromTemplate: Boolean, // Corrigido para Boolean
  pollInvalidated: Boolean,
  isSentCagPollCreation: Boolean,
  broadcast: Boolean,
  mentionedJidList: Array,
  quotedMsg: Object,
  quotedStanzaID: String,
  quotedRemoteJid: String,
  quotedParticipant: String,
  groupMentions: Array,
  isVcardOverMmsDocument: Boolean,
  labels: Array,
  hasReaction: Boolean,
  ephemeralSettingTimestamp: Number,
  disappearingModeInitiator: String,
  productHeaderImageRejected: Boolean,
  lastPlaybackProgress: Number,
  isDynamicReplyButtonsMsg: Boolean,
  isMdHistoryMsg: Boolean,
  stickerSentTs: Number,
  isAvatar: Boolean,
  requiresDirectConnection: Boolean,
  pttForwardedFeaturesEnabled: Boolean,
  chatId: String,
  fromMe: Boolean,
  sender: Object,
  timestamp: Number,
  isDeleted: Boolean,
  transcribeAudio: String,
  transcribeImage: String,
  caption: String,
  ticketId: { type: Schema.ObjectId, ref: 'tickets' },
  userId: { type: Schema.ObjectId, ref: 'usuarios' },
  ai_order_lead_id: { type: Schema.ObjectId, ref: 'ai_orders_leads' },

  // Campos adicionados
  viewed: Boolean,
  invis: Boolean,
  lat: Number,
  lng: Number,
  isEventCanceled: Boolean,
  eventInvalidated: Boolean,
  isForwarded: Boolean,
  latestEditMsgKey: String,
  latestEditSenderTimestampMs: Number,
  botResponseTargetId: String,
  botPluginType: String,
  botPluginReferenceIndex: String,
  botPluginSearchProvider: String,
  botPluginSearchUrl: String,
  botPluginSearchQuery: String,
  botPluginMaybeParent: Boolean,
  botReelPluginThumbnailCdnUrl: String,
  botMsgBodyType: String,
  profilePicThumbObj: {
    eurl: String,
    id: String,
    img: String,
    imgFull: String,
    tag: String
  },
  mediaData: Object,
  vcardList: Array,
  reprocess: Boolean,
  resend: Boolean,
  isLid: Boolean,
  chatLid: String,
  contact: Object,
  lid: Object,
  phoneNumber: Object,
  template: Object,
  url: String,
  media: Object,
  chatPhone: String,
  externalAdReply: Object,
  errorMessage: {
    code: Number,
    message: String
  }
});

module.exports = User = mongoose.model('whatsapp_mensagens', WhatsappMensagensSchema);
